name: Main

on:
  push:
  pull_request:
    paths-ignore:
    - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        id: build
        run: docker build . -t dvfdocker/owlcms4:latest
        shell: bash
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Go offline using the pom.xml
        run: mvn dependency:go-offline package -P production -am -pl owlcms -Dmaven.test.skip=true
      - name: Build
        run: mvn clean package -P production -am -pl owlcms -Dmaven.test.skip=true
      - name: Run tests
        run: mvn verify -am -pl owlcms